version: '3.8'
services:
  sigado-api:
    container_name: sigado-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: sigado-db
